### ISSUE TITLE
wikiparser not working

### ISSUE THREAD

**Issue by Reubencfernandes** [KiranNiranjan/wiki-parser-js#1]
i installed it and i get this 
`module.js:550

    throw err;

    ^

Error: Cannot find module 'wikiparser'

    at Function.Module._resolveFilename (module.js:548:15)

    at Function.Module._load (module.js:475:25)

    at Module.require (module.js:597:17)

    at require (internal/module.js:11:18)

at Object.<anonymous> (/app/app.js:27:12)

    at Module._compile (module.js:653:30)

    at Object.Module._extensions..js (module.js:664:10)

    at Module.load (module.js:566:32)

    at tryModuleLoad (module.js:506:12)

    at Function.Module._load (module.js:498:3)`

**Comment by KiranNiranjan** [comment]
@gco360 Can you provide more info such as `operating system` & `node version`
